"""001_create_core_tables

Revision ID: 6c8e6fefc46f
Revises: 
Create Date: 2026-06-11 09:38:47.478651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6c8e6fefc46f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # PostgreSQL native ENUM for Turno.estado
    # Drop if exists to handle partial previous runs
    op.execute(text("DROP TYPE IF EXISTS turno_estado_enum CASCADE"))
    turno_estado_enum = postgresql.ENUM(
        'DISPONIBLE', 'RESERVADO_TEMPORAL', 'CONFIRMADO', 'CANCELADO', 'COMPLETADO',
        name='turno_estado_enum', create_type=False
    )
    turno_estado_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('paciente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('apellido', sa.String(length=255), nullable=False),
    sa.Column('dni', sa.String(length=50), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('profesional',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('especialidad', sa.String(length=255), nullable=False),
    sa.Column('duracion_turno', sa.Integer(), nullable=False),
    sa.Column('horario_inicio', sa.String(length=5), nullable=False),
    sa.Column('horario_fin', sa.String(length=5), nullable=False),
    sa.Column('dias_atencion', sa.JSON(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lista_de_espera',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_solicitada', sa.Date(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notificado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turno',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('estado', turno_estado_enum, nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('profesional_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('hora_fin > hora_inicio', name='ck_turno_horario_valido'),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesional.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_turno_estado', 'turno', ['estado'], unique=False)
    op.create_index('ix_turno_fecha_hora_inicio', 'turno', ['fecha', 'hora_inicio'], unique=False)
    op.create_index('ix_turno_paciente_id_estado', 'turno', ['paciente_id', 'estado'], unique=False)
    op.create_table('reserva_temporal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.Column('expiracion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['turno_id'], ['turno.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turno_id')
    )
    op.create_index('ix_reserva_temporal_expiracion', 'reserva_temporal', ['expiracion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reserva_temporal_expiracion', table_name='reserva_temporal')
    op.drop_table('reserva_temporal')
    op.drop_index('ix_turno_paciente_id_estado', table_name='turno')
    op.drop_index('ix_turno_fecha_hora_inicio', table_name='turno')
    op.drop_index('ix_turno_estado', table_name='turno')
    op.drop_table('turno')
    op.drop_table('lista_de_espera')
    op.drop_table('profesional')
    op.drop_table('paciente')
    # Drop PostgreSQL native ENUM
    turno_estado_enum = postgresql.ENUM(
        'DISPONIBLE', 'RESERVADO_TEMPORAL', 'CONFIRMADO', 'CANCELADO', 'COMPLETADO',
        name='turno_estado_enum'
    )
    turno_estado_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
